In [1]:
u = [2, 2] 
v = [1, 2]
z = [-3,5]

In [2]:
result = []

In [3]:
for i in range(len(u)):
 result.append(u[i] + v[i] + z[i])

In [4]:
print(result)

[0, 9]


In [5]:
result = [sum(t) for t in zip(u, v, z)]


In [6]:
print(result)

[0, 9]


In [7]:
import numpy as np

In [8]:
nu = np.array([2,2])
nv = np.array([1,2])
nz = np.array([-3,5])

In [9]:
sum = nu + nv + nz
print(sum)

[0 9]


In [10]:
u = [ 1, 2, 3 ]
v = [ 4, 3, 3 ]
alpha = 2

In [11]:
del sum

In [12]:
result = [alpha * sum(t) for t in zip(u, v)]
print(result)

[10, 10, 12]


In [13]:
nu = np.array([1,2,3])
nv = np.array([4,3,3])
alpha = 2
result = (nu + nv ) * alpha
print(result)

[10 10 12]


In [14]:
matrix_a = [[3, 6], [4, 5]]
matrix_b = [[5, 8], [6, 7]]

In [15]:
result = [[sum(row) for row in zip(*t)] for t in zip(matrix_a,matrix_b)]
print(result)

[[8, 14], [10, 12]]


In [16]:
for t in zip(matrix_a,matrix_b):
    print(*t)

[3, 6] [5, 8]
[4, 5] [6, 7]


In [17]:
nmatrix_a = np.array ([[3,6], [4,5]])
nmatrix_b = np.array ([[5,8], [6,7]])

result = nmatrix_a + nmatrix_b
print(result)

[[ 8 14]
 [10 12]]


In [18]:
matrix_a = ([[1,2,3] , [4,5,6]])
c = np.transpose(matrix_a, (1,0))
print(c)


[[1 4]
 [2 5]
 [3 6]]


In [19]:
matrix_a = [[1,2,3], [4,5,6]]

In [20]:
def transpose(matrix):
    rows = []
    trans_matrix = []
    nrows = len(matrix_a)
    ncols = len(matirx_a[0])
               
    for i in range(ncols):
        for j in range(nrows):
            rows.append(matrix[j][i])
        trans_matrix.append(rows)
        rows = []
                
    return trans_matrix
print(transpose(matrix_a))

NameError: name 'matirx_a' is not defined